project:
  type: website

website:
  title: "Samuel Calderon"
  site-url: https://calderonsamuel.github.io/web
  description: "Web de Samuel Calderon"
  navbar:
    background: "#f6eee9"
    foreground: "#0A0A0A"
    # left:
    #   - href: index.qmd
    #     text: Home
    right: 
      - href: index.qmd
        text: "Acerca de mí"
      - href: projects/index.qmd
        text: "Proyectos"
      - href: posts/index.qmd
        text: "Blog"
      - href: "https://twitter.com/samucalse"
        icon: "twitter"
      - href: "https://github.com/calderonsamuel"
        icon: "github"

format:
  html:
    theme: 
      - sandstone
      - styles.scss
    toc: true


execute: 
  freeze: true
